### ISSUE TITLE
[BUG] CBPM not aligned with paper

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#170]
The CBPM method we implemented has slight variations from the original: using the mean instead of sum for summation; the weighting might also not be aligned.
While this should not make a fundamental difference, users should at least have the option to exactly follow the paper.

**Comment by kaurao** [comment]
the code from authors is available here: https://www.nitrc.org/projects/bioimagesuite/
the only difference I can notice is what @samihamdan mentioned, using `sum` instead of `mean`.

**Comment by NevenaK** [comment]
Thanks for the issue @samihamdan! I am using the CBPM implementation and would like to see if/what difference sum vs mean makes. And would also like to use it as the authors intended :) If I can help adjusting that, let me know :)

**Comment by kaurao** [comment]
The `mean` versus `sum` should not make any difference to predictions as the difference is same linear transformation across observations (just multiplying features with a constant). The linear model used for learning will take care of this and the predictions will be the same. The difference will be the weights assigned to the two features (`pos` and `neg`) but they will be again proportional so that should not be an issue as well. But I still agree that `sum` should be available to users.

Here is empirical demonstration of this using R ;)

```
# generate data
set.seed(1)
x1 = rnorm(100)
x2 = rnorm(100)
y = x1 + x2
# get a linear model
l1 = lm(y~., data=data.frame(y=y,x1=x1,x2=x2))
# get a linear model with scaled x
l2 = lm(y~., data=data.frame(y=y,x1=10*x1,x2=5*x2))
# plot
plot(l1$fitted.values, l2$fitted.values, xlab='l1', ylab='l2')
```

![image](https://user-images.githubusercontent.com/10744124/187879311-55562ecf-1559-48b8-a41f-be6df7a27164.png)

**Comment by NevenaK** [comment]
Nice, thank you!

**Comment by samihamdan** [comment]
This PR: #221  introduces sum as default option for cbpm, but still allows other aggregation functions.
