### ISSUE TITLE
More Tests & Documentation

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#23]
We need more testing & documentation.

I will focus on the lower level parts and add more tests and docstrings to them.

**Comment by fraimondo** [comment]
Agree.

Indeed before releasing, we need to unit test confound removal and target transform. And both applied at the same time.

I already tested a pipeline against sklearn, but without confounds or target transform. I still need to go deeper and check that the actual model is fit in the same way, rather than the predicted class of each sample.

I will set up CI for coverage, to see how we are doing on this side.

**Comment by fraimondo** [comment]
We now use codecov.io.

We are at 31.21%, we need to reach 90% for this issues to be closed.

**Comment by fraimondo** [comment]
Fixed a coverage issue, we are at 80.29.

@samihamdan Are the pipeline tests (https://github.com/juaml/julearn/blob/main/julearn/tests/test_pipeline.py) checking for correct data or just checking that the code runs?

**Comment by samihamdan** [comment]
They are checking both to some degree. 
But it is not only about coverage. There is a need for testing some things just more extensively. 
I will add more tests for Confound Removal target transformation and the pipeline asap.

**Comment by samihamdan** [comment]
We reached the aimed test coverage and added a lot of the basic documentation. 
Both documentation and tests will be an ongoing task, but this aim of this issue and milestone was fulfilled.
