### ISSUE TITLE
[ENH] More restrictive Column Type System

### ISSUE THREAD

**Issue by samihamdan** [juaml/julearn#55]
We started this conversation already when looking and the `ConfoundRemover`. 
Some parts of julearn are still too flexible and allow too many inputs. 

What do you @fraimondo think about following things: 
1. Column Type System always with the same delimiter. 
Originally, I baked in the possibility of changing the delimiter from `'__:type:__'` to anything else.  
For the `ConfoundRemover` we already changed this, so that the delimiter is always a '__:type:__'. 
But we also introduced the usage of regex to define the confounds. 
I would like to do so for all the other classes as well. Keeping only `'__:type:__'` as delimiter and providing regex capability where users would define confounds, categorical variables etc.

2. Column Type System provided types
Currently, some of the elements allow in theory user defined column types.  
So, that not only our supported types: continuous, categorical and confound, but also not predefined once work.
While I think such a function could be handy at some points I also assume that this flexibility might lead to unexpected problems.  
I would currently tend to remove this option and only allow predefined types. What do you think ?

**Comment by fraimondo** [comment]
> We started this conversation already when looking and the `ConfoundRemover`.
> Some parts of julearn are still too flexible and allow too many inputs.
> 
> What do you @fraimondo think about following things:
> 
> 1. Column Type System always with the same delimiter.
>    Originally, I baked in the possibility of changing the delimiter from `'__:type:__'` to anything else.
>    For the `ConfoundRemover` we already changed this, so that the delimiter is always a '**:type:**'.
>    But we also introduced the usage of regex to define the confounds.
>    I would like to do so for all the other classes as well. Keeping only `'__:type:__'` as delimiter and providing regex capability where users would define confounds, categorical variables etc.

You make it sound even more complicated than it is. It is already done in the `run_cross_validation`. Check https://github.com/juaml/julearn/blob/bf92ca318a5a57be26a689c02e0fe67d0faee27a/julearn/prepare.py#L202

When you implemented it in `DataFrameConfoundRemover`, you named it `confounds_match`. I would just name it confounds and allow whatever string or list of strings is there. Then, when fitted, I'll call `pick_columns` and that will be it.


> 2. Column Type System provided types
>    Currently, some of the elements allow in theory user defined column types.
>    So, that not only our supported types: continuous, categorical and confound, but also not predefined once work.
>    While I think such a function could be handy at some points I also assume that this flexibility might lead to unexpected problems.
>    I would currently tend to remove this option and only allow predefined types. What do you think ?

What would be the issue, and where do you want to restrict this? We need these 3 categories so that confounds are removed only from the continuous variables and not the categorical. If the user gives a column name `:__type__:ordinal` then it will not be a confound, nor be deconfounded as it is not continuous.

You can raise a warning here https://github.com/juaml/julearn/blob/bf92ca318a5a57be26a689c02e0fe67d0faee27a/julearn/prepare.py#L69 if there is something named `:__type__:` and It does not match what's in X, y and z. For example, use `:__type__:confound` as y, or `:__type__:confound` not in `confounds`. Or use a type that's not 'continuous', 'categorical' or confound.

**Comment by fraimondo** [comment]
@samihamdan Are we dropping the column type system?

**Comment by samihamdan** [comment]
We change the Column Type System in #183
