### ISSUE TITLE
[ENH] Access pipeline elements by name

### ISSUE THREAD

**Issue by fraimondo** [juaml/julearn#8]
Again, trying to write an example to inspect a random forest and I found that it is quite difficult to get to the classifier object.

First I run this:
```Python
scores, model_iris = run_cross_validation(X=X, y=y, data=df_iris, model='rf',
                                          return_estimator=True)
```

If I want to access the classifier, I need to do this:
```Python
rf = model_iris.dataframe_pipeline['rf']
```

I would like to do this:
```Python
rf = model_iris['rf']
```

I would just implement the `__getitem__` method in the `ExtendedDataFramePipeline` and pass it to the `dataframe_pipeline`, unless the item starts with `confound_`, in which it should be used to access the `confound_dataframe_pipeline`.

@samihamdan  do you agree?

**Comment by samihamdan** [comment]
Yes these things were planned, but not yet implemented. 
I think a `__getitem__` would be sufficient. 
Additionally, I planned to follow `sklearn.pipe.Pipline` convetions. 
Instead of `steps` and `named_steps` we could use steps for each subpart of the `ExtendedDataFramePipeline`. 
So, for `target_steps`, `confound_steps` and `feature_steps`. 
But I think providing both ways might be easiest for users. 

I think we have to make sure that the naming conventions we use here for confounds, features and target stay the same through julearn. For example with setting hyper parameters etc.

**Comment by fraimondo** [comment]
I already aded the `__getitem__` in my PR. Can you update yours?

**Comment by samihamdan** [comment]
Yeah saw that too late. 
I close the old PR, because there is some confusion going on. 
Merged the functionality with another PR
